name: java-graalvm-development-workflow

on:
  workflow_call:
    inputs:
      functionName:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  BUILD:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "☕️ Set up JDK 11 for x64"
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - name: "☕️ Setup GraalVM CE"
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "✅ Verify versions"
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          gu --version
          native-image --version
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: "📸 Build the Native Binary"
        run: |
          mvn package -Dpackaging=docker-native -Dexec.mainClass=io.micronaut.function.aws.runtime.MicronautLambdaRuntime -Dmicronaut.runtime=lambda -Pgraalvm -DskipTests
      - name: Archive Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{inputs.functionName}}
          path: target/
          retention-days: 1

  DEPLOY_DEV: 
    needs: BUILD
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: ${{inputs.functionName}}
          path: target/
      - name:  "Deploy the Native Binary to AWS Development"
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{inputs.functionName}}
          zip_file: target/function.zip
